### ISSUE TITLE
Compatible with torch.utils.tensorboard

### ISSUE THREAD

**Issue by RylanSchaeffer** [cheind/tf-matplotlib#5]
Is this library compatible with Pytorch's `torch.utils.tensorboard`?

**Comment by cheind** [comment]
Hi, for PyTorch I'm using the internal [API](https://pytorch.org/docs/stable/tensorboard.html). In particular the function `add_figure` covers most of what tf-matplotlib does.

**Comment by RylanSchaeffer** [comment]
Thanks for the tip!
Cheers,
Rylan Schaeffer
